### ISSUE TITLE
CC1 and CC2 statically pulling up

### ISSUE THREAD

**Issue by Citrullin** [alvarop/debugotron#1]
Just a question to get confirmation. So, if I pull CC1 and CC2 up to 0.42V, I would just get always the default 500 mA.
Do I get this right, or am I missing something here?

**Comment by Citrullin** [comment]
I was thinking about the TPS62800, which is available right now. The FAN53528 would be even more interesting, but the target voltage is even off by more. Do you know what the tolerances are here?

**Comment by alvarop** [comment]
From https://www.usb.org/sites/default/files/USB%20Type-C%20Spec%20R2.0%20-%20August%202019.pdf

So they specify it as pull-up resistors for various currents:
![image](https://user-images.githubusercontent.com/744129/207472602-ad059287-e981-47c2-a1d4-1ac19ac0e82c.png)

They have recommended resistors depending on pull up voltage, but also have current source examples:
![image](https://user-images.githubusercontent.com/744129/207472657-ec6fe375-9f30-488b-ae8a-c30b1d28f32f.png)

In your case, pulling both up to 0.42V would not be a valid setting for Debug Accessory Mode, since CC1 and CC2 never match in that case. See the first table above for the settings

**Comment by Citrullin** [comment]
> From https://www.usb.org/sites/default/files/USB%20Type-C%20Spec%20R2.0%20-%20August%202019.pdf
> 
> So they specify it as pull-up resistors for various currents: ![image](https://user-images.githubusercontent.com/744129/207472602-ad059287-e981-47c2-a1d4-1ac19ac0e82c.png)
> 
> They have recommended resistors depending on pull up voltage, but also have current source examples: ![image](https://user-images.githubusercontent.com/744129/207472657-ec6fe375-9f30-488b-ae8a-c30b1d28f32f.png)
> 
> In your case, pulling both up to 0.42V would not be a valid setting for Debug Accessory Mode, since CC1 and CC2 never match in that case. See the first table above for the settings

You got a point here. I missed that somehow.
